server:
  shutdown: immediate

oauth:
  endpoint.url: http://localhost:8090/auth

spring:
  datasource:
    url: 'jdbc:h2:mem:audit-db;MODE=PostgreSQL'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  flyway:
    locations: classpath:/db/migration/h2,classpath:/db/migration/common
