graceful:
  shutdown.enabled: false

aws:
  provider: localstack

hmpps.sqs:
  localstackUrl: http://localhost:4566
  queues:
    main:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}

spring:
  jpa:
    show-sql: true
