graceful:
  shutdown.enabled: false

aws:
  provider: localstack
  athena:
    database: database_name
    table: table
    workgroup: workgroup
    outputLocation: output-location
    prisonerDatabase: prisoner-database
    prisonerTable: prisoner-table
    prisonerWorkgroup: prisonerWorkgroup
    prisonerOutputLocation: prisonerOutputLocation

hmpps.sqs:
  provider: localstack
  queues:
    auditqueue:
      queueName: mainQueue
      asyncQueueClient: true
      dlqName: mainDlq
    auditusersqueue:
      queueName: auditUsersQueue
      asyncQueueClient: true
      dlqName: auditUsersDlq
    prisonerauditqueue:
      queueName: prisonerQueue
      asyncQueueClient: true
      dlqName: prisonerDlq

spring:
  jpa:
    show-sql: true
