server:
  shutdown: immediate
  port: 8081

oauth:
  endpoint.url: http://localhost:9090/auth

spring:
  datasource:
    url: 'jdbc:h2:mem:audit-db;MODE=PostgreSQL'
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
  flyway:
    locations: classpath:/db/migration/h2,classpath:/db/migration/dev/data,classpath:/db/migration/common

hmpps:
  repository:
    saveToS3Bucket: true
  audit:
    queriesStartDate: 2024-01-01
  sqs:
    provider: localstack
    queues:
      auditqueue:
        queueName: mainQueue
        asyncQueueClient: true
        dlqName: mainDlq
      auditusersqueue:
        queueName: auditUsersQueue
        asyncQueueClient: true
        dlqName: auditUsersDlq
      prisonerauditqueue:
        queueName: prisonerQueue
        asyncQueueClient: true
        dlqName: prisonerDlq