graceful:
  shutdown.enabled: false

aws:
  provider: localstack

hmpps.sqs:
  provider: localstack
  queues:
    auditqueue:
      queueName: mainQueue
      asyncQueueClient: true
      dlqName: mainDlq
    auditusersqueue:
      queueName: mainQueue
      asyncQueueClient: true
      dlqName: mainDlq

spring:
  jpa:
    show-sql: true
