spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit-db
    username: admin
    password: admin_password
  flyway:
    locations: classpath:/db/audit,/db/audit_postgres
    schemas: staff,prisoner
    default-schema: staff
oauth:
  endpoint.url: http://localhost:9090/auth
