graceful:
  shutdown.enabled: false

aws:
  provider: localstack

hmpps.sqs:
  provider: localstack
  queues:
    auditqueue:
      queueName: mainQueue
      asyncQueueClient: true
      dlqName: mainDlq
    auditusersqueue:
      queueName: auditUsersQueue
      asyncQueueClient: true
      dlqName: auditUsersDlq
    prisonerauditqueue:
      queueName: prisonerQueue
      asyncQueueClient: true
      dlqName: prisonerDlq

spring:
  jpa:
    show-sql: true
