# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/hmpps-audit-api
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: audit-api-preprod.hmpps.service.justice.gov.uk
      cert_secret: audit-api-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
