# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:

  replicaCount: 4

  ingress:
    host: audit-api-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '35 6 * * 1-5' # Start at 6:35am UTC Monday-Friday
    shutdown: '35 21 * * 1-5' # Stop at 9:35pm UTC Monday-Friday

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
  rdsAlertsDatabases:
    cloud-platform-cc2530362d2e4b5a: "hmpps audit api"
