# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Environment specific values, override helm_deploy/hnpps-audit-api/values.yaml
generic-service:
  replicaCount: 4
  ingress:
    host: audit-api.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "https://hmpps-auth.hmpps-auth-prod.svc.cluster.local/auth"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
  rdsAlertsDatabases:
    cloud-platform-a041fe0b2e6de452: "hmpps audit api"
