# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Environment specific values, override helm_deploy/hnpps-audit-api/values.yaml
generic-service:
  replicaCount: 4
  ingress:
    host: audit-api.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
