# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Environment specific values, override helm_deploy/hnpps-audit-api/values.yaml
generic-service:
  replicaCount: 4
  ingress:
    host: audit-api.hmpps.service.justice.gov.uk

  env:
    OAUTH_ENDPOINT_URL: "http://hmpps-auth.hmpps-auth-prod.svc.cluster.local/auth"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SAVE_TO_S3_BUCKET: false

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
  sqsNumberAlertQueueMappings:
    staff:
      - "Digital-Prison-Services-prod-hmpps_audit_queue"
      - "Digital-Prison-Services-prod-hmpps_audit_dlq"
    Prisoner:
      - "Digital-Prison-Services-prod-hmpps_prisoner_audit_queue"
      - "Digital-Prison-Services-prod-hmpps_prisoner_audit_dlq"
    user:
      - "Digital-Prison-Services-prod-hmpps_audit_users_queue"
      - "Digital-Prison-Services-prod-hmpps_audit_users_dlq"
  rdsAlertsDatabases:
    cloud-platform-a041fe0b2e6de452: "hmpps audit api"
