name: environment_integration_test.yml

on:
  workflow_call:
    inputs:
      env_test_url:
        required: true
        type: string
      job_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      OAUTH_CLIENT_ID:
        required: true
      OAUTH_CLIENT_SECRET:
        required: true
      OAUTH_TOKEN_URL:
        required: true

permissions:
  contents: read

jobs:
  run-integration-test:
    name: ${{ inputs.job_name }}
    environment: ${{ inputs.environment }}
    runs-on: [self-hosted, hmpps-github-actions-runner]
    env:
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      OAUTH_TOKEN_URL: ${{ secrets.OAUTH_TOKEN_URL }}
      ENV_TEST_URL: ${{ inputs.env_test_url }}
    steps:
      - name: Get OAuth token
        id: get_token
        shell: bash
        run: |
          BASIC_AUTH=$(echo -n "$OAUTH_CLIENT_ID:$OAUTH_CLIENT_SECRET" | base64 | tr -d '\n')
          RESPONSE=$(curl --fail --verbose -s -X POST "$OAUTH_TOKEN_URL?grant_type=client_credentials" \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $BASIC_AUTH")
          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Failed to extract access token."
            echo "Response was: $RESPONSE"
            exit 1
          fi
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Step 1 - Create audit event
        id: create_event
        run: |
          RESPONSE=$(curl --fail --verbose --silent --show-error \
            -X POST "$ENV_TEST_URL/internal/integration-test/audit-event" \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
            -H "Content-Type: application/json")
          
          echo "Audit event response: $RESPONSE"
          echo "$RESPONSE" > audit_event.json

      - name: Step 2 - Trigger repair partitions
        id: trigger_repair
        run: |
          RESPONSE=$(curl --fail --verbose --silent --show-error \
            -X POST "$ENV_TEST_URL/audit/query/repair-partitions" \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
            -H "Content-Type: application/json")
          
          echo "Repair response: $RESPONSE"
          echo "$RESPONSE" > repair_response.json
          QUERY_EXECUTION_ID=$(echo "$RESPONSE" | jq -r '.queryExecutionId')
          echo "queryExecutionId=$QUERY_EXECUTION_ID" >> $GITHUB_OUTPUT

      - name: Step 3 - Wait for repair partitions to complete
        run: |
          QUERY_ID=${{ steps.trigger_repair.outputs.queryExecutionId }}
      
          echo "Polling query execution status for ID: $QUERY_ID"
      
          for attempt in {1..60}; do
            RESPONSE=$(curl --fail --silent --show-error \
              -X GET "$ENV_TEST_URL/audit/query/repair-partitions/$QUERY_ID" \
              -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
              -H "Content-Type: application/json")
      
            echo "Attempt $attempt: $RESPONSE"
      
            QUERY_STATE=$(echo "$RESPONSE" | jq -r '.queryState')
      
            if [[ "$QUERY_STATE" == "SUCCEEDED" ]]; then
              echo "Query execution succeeded."
              break
            elif [[ "$QUERY_STATE" == "FAILED" || "$QUERY_STATE" == "CANCELLED" ]]; then
              echo "Query execution failed with state: $QUERY_STATE"
              exit 1
            fi
      
            echo "Query still in progress (state: $QUERY_STATE). Waiting 20 seconds..."
            sleep 20
          done
      
          if [[ "$QUERY_STATE" != "SUCCEEDED" ]]; then
            echo "Timed out waiting for query to succeed after 20 minutes."
            exit 1
          fi

      - name: Step 4 - Trigger audit event query
        id: trigger_audit_query
        run: |
          RESPONSE=$(curl --fail --silent --show-error --verbose \
            -X POST "$ENV_TEST_URL/internal/integration-test/query" \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
          
          echo "Trigger audit query response: $RESPONSE"
          QUERY_EXECUTION_ID=$(echo "$RESPONSE" | jq -r '.queryExecutionId')
          echo "queryExecutionId=$QUERY_EXECUTION_ID" >> $GITHUB_OUTPUT


